### ISSUE TITLE
Workshop milestone

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-moco#77]
Tasks required to achieve the January milestone for the Dynamic Walking workshop:

- [x] tracking whole-body walking with markers.
- [ ] contact (not relying on residual force to support or propel the model).
- [ ] GRF tracking
- [x] torque muscles (muscle-like coordinate actuators).
- [ ] Copy Q and U into the solution for MocoInverse.

Optional:

- [ ] path-based muscles
